spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/myShopProject
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  tymeleaf:
    prefix: classpath:/templates/
    suffix: .html
logging.level:
  org.hibernate.SQL: debug